services:
  ubuntu-terminal:
    build: ./ubuntu_bash
    container_name: ubuntu_bash
    command: ttyd -W bash
    ports:
      - "7681:7681"
    tty: true
    stdin_open: true

  webserver:
    image: nginx:alpine
    container_name: web_portal
    ports:
      - "8080:80"
    volumes:
      - ./nginx:/usr/share/nginx/html:Z
    depends_on:
      - ubuntu-terminal
